link_with 'MFMigrationManager.iOS', 'MFMigrationManager.iOS.Tests', 'MFMigrationManager.Mac', 'MFMigrationManager.Mac.Tests'

podspec :path => "../MFMigrationManager.podspec"
pod 'Kiwi/XCTest', '~> 2.2.4'